version: "3.3"
services:

  backend:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: 'true'
    command: bash -c "python ddd/init.py && uvicorn --reload --host 0.0.0.0 ddd.api.web:app"
